version: "2"

linters:
  enable:
    # Bugs
    - bodyclose
    - durationcheck
    - errcheck
    - exhaustive
    - forcetypeassert
    - govet
    - nilerr
    - noctx
    - staticcheck

    # Error handling
    - errorlint
    - errname
    - wrapcheck

    # Performance
    - copyloopvar
    - intrange
    - prealloc
    - perfsprint
    - unconvert

    # Style & maintainability
    - goconst
    - gocritic
    - goprintffuncname
    - misspell
    - modernize
    - nakedret
    - nestif
    - nolintlint
    - predeclared
    - revive
    - usestdlibvars
    - wastedassign
    - whitespace

    # Unused code
    - ineffassign
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
    govet:
      enable-all: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    exhaustive:
      default-signifies-exhaustive: true
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    nolintlint:
      require-explanation: true
      require-specific: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    wrapcheck:
      ignore-sigs:
        - fmt.Errorf(

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dirien/pulumi-ccstatusline

output:
  sort-order:
    - linter
    - file
