version: 2
project_name: pulumi-ccstatusline

before:
  hooks:
    - go mod tidy

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}.{{ .Os }}-{{ .Arch }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - repository:
      owner: dirien
      name: homebrew-dirien
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/dirien/pulumi-ccstatusline"
    description: "A Claude Code status line tool that displays Pulumi stack information"
    license: "Apache-2.0"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
